version: "3"
services:
  #PHP Service
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    # restart:
    command: sh -c 'composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction && php artisan migrate && php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

  #MySQL Service
  db:
    image: "mysql:8.0-oracle"
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "./database/initdb:/docker-entrypoint-initdb.d"
      - "./data/mysql:/var/lib/mysql"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

#Docker Networks
networks:
  app-network:
    driver: bridge
