version: "3"
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - "./database/initdb:/docker-entrypoint-initdb.d"
      - "./data/mysql:/var/lib/mysql"
    networks:
      - lms
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - "./data/redis:/data"
  #   networks:
  #     - lms
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     retries: 3
  #     timeout: 5s
  lms:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    # redis:
    #   condition: service_healthy
    networks:
      - lms

networks:
  lms:
    driver: bridge
